core/urls.py
from django.urls import include, path
from core import views

from admin_notification.views import check_notification_view



app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("products/", views.product_list_view, name="product-list"),

    path("newsletter/", views.newsletter, name ="newsletter"),


    
    ################ PRODUCT ###############
    path("product/<pid>/", views.product_detail_view, name="product-detail"),
    # path("about/", about_view, name="about"),



    ########################   CATEGORY   ########################
    path("category/", views.category_list_view, name="category-list"),
    path("category/<cid>/", views.category_product_list_view, name="category-product-list"),


    ############################  VENDOR  ####################
    path("vendors/", views.vendor_list_view, name="vendor-list"),
    path("vendors/<vid>/", views.vendor_detail_view, name="vendor-detail"),


    ############## tags###########################
    path("products/tag/<slug:tag_slug>/", views.tag_list, name="tags"),

    ### Add review
    path("ajax-add-review/<int:pid>/", views.ajax_add_review, name="ajax-add-review"),

    #search
    path("search/", views.search_view, name="search"),

    #filter 
    path("filter-products/", views.filter_product, name="filter-product"),

    ####Add to cart
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),

    ## Cart page 
    path("cart/", views.cart_view, name="cart"),

    path("delete-from-cart/", views.delete_item_from_cart, name="delete-from-cart"),

        #### Update cart
    path("update-cart/", views.update_cart, name="update-cart"),


    # Checkout  URL
    path("checkout/", views.checkout_view, name="checkout"),

    #Paypal URL
    path('paypal/', include('paypal.standard.ipn.urls')),

     # Payment Successful
    path("payment-completed/", views.payment_completed_view, name="payment-completed"),

    # Payment Failed
    path("payment-failed/", views.payment_failed_view, name="payment-failed"),

     # Dahboard URL
    path("dashboard/", views.customer_dashboard, name="dashboard"),

    # Order Detail URL
    path("dashboard/order/<int:id>", views.order_detail, name="order-detail"),

    # Making address defauly
    path("make-default-address/", views.make_address_default, name="make-default-address"),

    # wishlist page
    path("wishlist/", views.wishlist_view, name="wishlist"),

    # adding to wishlist
    path("add-to-wishlist/", views.add_to_wishlist, name="add-to-wishlist"),


    # Remvoing from wishlist
    path("remove-from-wishlist/", views.remove_wishlist, name="remove-from-wishlist"),


    path("contact/", views.contact, name="contact"),
    path("ajax-contact-form/", views.ajax_contact_form, name="ajax-contact-form"),

        ############ABOUT###########
    path("about_us/", views.about_us, name="about_us"),
    path("best_Price/", views.best_price, name="best_price"),
    path("wide_assortment/", views.wide_assortment, name="wide_assortment"),
    path("free_delivery/", views.free_delivery, name="free_delivery"),
    path("easy_returns/", views.easy_returns, name="easy_returns"),
    path("great_deal/", views.great_deal, name="great_deal"),
    path("satisfaction/", views.satisfaction, name="satisfaction"),

       ###############

    path("purchase_guide/", views.purchase_guide, name="purchase_guide"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
    path("terms_of_service/", views.terms_of_service, name="terms_of_service"),


    #Notification

    path('check/notification/', check_notification_view, name="check_notifications"),










]

ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from admin_notification.views import check_notification_view


urlpatterns = [
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('secret/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("useradmin/", include("useradmin.urls")),
    path("payments/", include("payments.urls")),

    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("", include("allauth.urls")),
    path('paystack/', include('paystack.urls')),

    path('check/notification', check_notification_view, name="check_notifications"),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

useradmin/urls.py
from django.urls import path
from useradmin import views

app_name = "useradmin"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("products/", views.dashboard_products, name="dashboard-products"),
    path("orders/", views.dashboard_orders, name="dashboard-orders"),
    path("add-products/", views.dashboard_add_product, name="dashboard-add-products"),
    path("edit-products/<pid>/", views.dashboard_edit_product, name="dashboard-edit-products"),
    path("delete-products/<pid>/", views.dashboard_delete_product, name="dashboard-delete-products"),

]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path('subscribe/', views.subscribe, name='subscribe'),
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('social/signup', views.signup_redirect, name='signup_redirect'),

    # path("newsletter", views.newsletter, name ="newsletter"),


    path("password-reset/", views.password_reset_request, name="reset-password"),
    path("password-change/", views.password_change, name="password-change"),
    path("reset/<uidb64>/<token>", views.passwordResetConfirm, name="password-reset-confirm"),

    path("profile/update/", views.profile_update, name="profile-update"),
]

core/models.py
from django.db import models

# Create your models here.
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.utils.html import mark_safe
from userauths.models import User
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField


STATUS_CHOICE = (
    ("processing", "Processing"),
    ("delivered", "Delivered"),
    ("shipped", "Shipped"),
)

STATUS = (
    ("draft", "Draft"),
    ("disabled", "Disabled"),
    ("rejected", "Rejected"),
    ("in_review", "In Review"),
    ("published", "Published"),
)

RATING = (
    (1, "★✰✰✰✰"),
    (2, "★★✰✰✰"),
    (3, "★★★✰✰"),
    (4,"★★★★✰"),
    (5,"★★★★★"),
)


def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)

# Create your models here.

class Category(models.Model):
    cid = ShortUUIDField(unique=True, length=10, max_length=20,
                         prefix="cat", alphabet="abcdefgh12345")
    title = models.CharField(max_length=100, unique=True, default="Food")
    image = models.ImageField(upload_to="category", default="category.jpg")
    date = models.DateTimeField(auto_now_add=True, null=True,blank=True)

    class Meta:
        verbose_name_plural = "Category"

    class MPTTMeta:
        order_insertion_by = ['title']

    def category_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title
    
class Tags(models.Model):
    pass


class Vendor(models.Model):
    vid = ShortUUIDField(unique=True, length=10, max_length=20,
                         prefix="ven", alphabet="abcdefgh12345")
    
    title = models.CharField(max_length=100, default="Adepa")
    cover_image = models.ImageField(upload_to=user_directory_path, default="vendor.jpg")

    image = models.ImageField(upload_to=user_directory_path, default="vendor.jpg")
    # description = models.TextField(null=True, blank=True, default="I sell good products only")
    description = RichTextUploadingField(null=True, blank=True, default="I sell good products only")


    address = models.CharField(
        max_length=200, default="123 Main street, Suame")
    contact = models.CharField(max_length=200, default="+233")
    shipping_on_time = models.CharField(max_length=200, default="100")
    chat_resp_time = models.CharField(max_length=200, default="100")
    authentic_rating = models.CharField(max_length=200, default="100")
    day_return = models.CharField(max_length=200, default="100")
    waranty_period = models.CharField(max_length=200, default="100")
    date = models.DateTimeField(auto_now_add=True, null=True,blank=True)

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    class Meta:
        verbose_name_plural = "Vendors"

    def vendor_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title


class Product(models.Model):
    pid = ShortUUIDField(unique=True, length=10, max_length=20, alphabet = "abcdefgh12345")

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name="category")
    vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL, null=True, related_name="product")


    title = models.CharField(max_length=100, default="Fresh pear")
    image = models.ImageField(upload_to=user_directory_path, default="product.jpg")
    # description = models.TextField(null=True, blank=True, default="This is the product")
    description = RichTextUploadingField(null=True, blank=True, default="I sell good products only")

    price = models.DecimalField(max_digits=99999999, decimal_places=2, default="1.99")
    old_price = models.DecimalField(max_digits=99999999, decimal_places=2, default="2.99")
    # specifications = models.TextField(null=True, blank=True, default="Black")
    specifications = RichTextUploadingField(null=True, blank=True, default="Black")

    type = models.CharField(max_length=100, default="Organic", null=True, blank=True)
    stock_count = models.CharField(max_length=100, default="8", null=True, blank=True)
    life = models.CharField(max_length=100, default="100", null=True, blank=True )
    size = models.CharField(max_length=100, default="L", null=True, blank=True )
    color = models.CharField(max_length=100, default="Blue", null=True, blank=True)
    mfd = models.DateTimeField(auto_now_add=False, null=True, blank=True)
 
    tags = TaggableManager(blank=True)

    product_status = models.CharField(choices=STATUS, max_length=10, default="in_review")
    

    status = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)
    digital = models.BooleanField(default=False)

    sku = ShortUUIDField(unique=True, length=4, max_length=10, prefix ="SKU", alphabet = "1234567890")

    date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(null=True, blank=True)



    class Meta:
        verbose_name_plural = "Products"

    def product_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title
    
    def get_percentage(self):
        new_price = (self.price - self.old_price) / (self.price) * 100
        return new_price
    
class ProductImages(models.Model):
    images = models.ImageField(upload_to="product_images", default="product.jpg")
    product = models.ForeignKey(Product, related_name="p_images", on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name_plural = "Product Images"


###################################cart, order, orderitems and address #######################
###################################cart, order, orderitems and address #######################
###################################cart, order, orderitems and address #######################
###################################cart, order, orderitems and address #######################





class CartOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=99999999, decimal_places=2, default="1.99")
    paid_status = models.BooleanField(default=False)
    order_date = models.DateTimeField(auto_now_add=True)
    product_status = models.CharField(choices=STATUS_CHOICE, max_length=30, default="processing")


    class Meta:
        verbose_name_plural = "Cart Order"



class CartOrderItem(models.Model):
    order = models.ForeignKey(CartOrder, on_delete=models.CASCADE)
    invoice_no = models.CharField(max_length=200)
    product_status = models.CharField( max_length=200,)
    item = models.CharField( max_length=200,)
    image = models.CharField( max_length=200,)
    qty = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=99999999, decimal_places=2, default="1.99")
    total = models.DecimalField(max_digits=99999999, decimal_places=2, default="1.99")

    class Meta:
        verbose_name_plural = "Cart Order Items"


    def order_img(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" />' % (self.image))



################################### product review, whishlist, address #######################
################################### product review, whishlist, address #######################
################################### product review, whishlist, address #######################
################################### product review, whishlist, address #######################
################################### product review, whishlist, address #######################

class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, related_name="reviews")
    review = models.TextField()
    rating = models.IntegerField(choices=RATING, default=None)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Product Reviews"

    def __str__(self):
        return self.product.title
    
    def get_rating(self):
        return self.rating
    

class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Wishlists"

    def __str__(self):
        return self.product.title

class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=300, null=True)
    email = models.CharField(max_length=300, null=True)
    mobile = models.CharField(max_length=200, null=True)
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Address"

useradmin/models.py
from django.db import models

# Create your models here.

useradmin/forms.py
from core.models import Product
from django import forms
# from bootstrap_datepicker_plus import DatePickerInput
from bootstrap_datepicker_plus.widgets import DateTimePickerInput



class AddProductForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Product Title", "class":"form-control"}))
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': "Product Description", "class":"form-control"}))
    price = forms.CharField(widget=forms.NumberInput(attrs={'placeholder': "Sale Price", "class":"form-control"}))
    old_price = forms.CharField(widget=forms.NumberInput(attrs={'placeholder': "Old Price", "class":"form-control"}))
    type = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Type of product e.g organic cream", "class":"form-control"}))
    stock_count = forms.CharField(widget=forms.NumberInput(attrs={'placeholder': "How many are in stock?", "class":"form-control"}))
    life = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "How long would this product live?", "class":"form-control"}))
    mfd = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'placeholder': "e.g: 22-11-02", "class":"form-control"}))
    tags = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Tags", "class":"form-control"}))
    image = forms.ImageField(widget=forms.FileInput(attrs={"class":"form-control"}))

    class Meta:
        model = Product
        fields = [
            'title',
            'image',
            'description',
            'price',
            'old_price',
            'specifications',
            'type',
            'stock_count',
            'life',
            'mfd',
            'tags',
            'digital',
            'category',
        ]

        widgets = {
        'mdf': DateTimePickerInput
    }

templates/useradmin/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <metaname="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0" >
    <title>AdepaMarket</title>

    <link rel="shortcut icon" type="image/x-icon"href="{% static 'assets3/img/favicon.png'%}"/>

    <link rel="stylesheet" href="{% static 'assets3/css/bootstrap.min.css'%}" />

    <link rel="stylesheet" href="{% static 'assets3/css/font-awesome.min.css'%}" />

    <link rel="stylesheet" href="{% static 'assets3/css/feathericon.min.css'%}" />

    <link rel="stylesheet" href="{% static 'assets3/plugins/morris/morris.css'%}" />

    <link rel="stylesheet" href="{% static 'assets3/css/style.css'%}" />
  </head>

  <body>
    <div class="">
      <div class="header">
        <div class="header-left">
          <a href="{% url 'core:index' %}" class="logo">
            <img style="object-fit: cover;" src="{% static 'assets2/imgs/theme/logo.svg' %}" alt="Logo" />
          </a>
          <a href="{% url 'core:index' %}" class="logo logo-small">
            <h3>Adepa</h3>
          </a>
        </div>

        <a href="javascript:void(0);" id="toggle_btn">
          <i class="fe fe-text-align-left"></i>
        </a>
        <div class="top-nav-search">
          <form>
            <input type="text" class="form-control" placeholder="Search here" />
            <button class="btn" type="submit">
              <i class="fa fa-search"></i>
            </button>
          </form>
        </div>

        <a class="mobile_btn" id="mobile_btn">
          <i class="fa fa-bars"></i>
        </a>

        <ul class="nav user-menu">
          <li class="nav-item dropdown noti-dropdown">
            <a href="#" class="dropdown-toggle nav-link" data-bs-toggle="dropdown">
              <i class="fa fa-bell"></i> <span class="badge badge-pill">3</span>
            </a>
            <div class="dropdown-menu notifications">
              <div class="topnav-dropdown-header">
                <span class="notification-title">Notifications</span>
                <a href="javascript:void(0)" class="clear-noti"> Clear All </a>
              </div>
              <div class="noti-content">
                <ul class="notification-list">
                  <li class="notification-message">
                    <a href="#">
                      <div class="media d-flex">
                        <span class="avatar avatar-sm flex-shrink-0">
                          <img class="avatar-img rounded-circle" alt="User Image" src="{% static 'assets3/img/profiles/avatar-02.jpg' %}"/>
                        </span>
                        <div class="media-body flex-grow-1">
                          <p class="noti-details">
                            <span class="noti-title">Carlson Tech</span> has
                            approved
                            <span class="noti-title">your estimate</span>
                          </p>
                          <p class="noti-time">
                            <span class="notification-time">4 mins ago</span>
                          </p>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li class="notification-message">
                    <a href="#">
                      <div class="media d-flex">
                        <span class="avatar avatar-sm flex-shrink-0">
                          <img class="avatar-img rounded-circle" alt="User Image" src="{% static 'assets3/img/profiles/avatar-11.jpg' %}"/>
                        </span>
                        <div class="media-body flex-grow-1">
                          <p class="noti-details">
                            <span class="noti-title">International Software Inc</span>has sent you a invoice in the amount of
                            <span class="noti-title">$218</span>
                          </p>
                          <p class="noti-time">
                            <span class="notification-time">6 mins ago</span>
                          </p>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li class="notification-message">
                    <a href="#">
                      <div class="media d-flex">
                        <span class="avatar avatar-sm flex-shrink-0">
                          <img class="avatar-img rounded-circle" alt="User Image" src="{% static 'assets3/img/profiles/avatar-17.jpg' %}"/>
                        </span>
                        <div class="media-body flex-grow-1">
                          <p class="noti-details">
                            <span class="noti-title">John Hendry</span> sent a
                            cancellation request
                            <span class="noti-title">Apple iPhone XR</span>
                          </p>
                          <p class="noti-time">
                            <span class="notification-time">8 mins ago</span>
                          </p>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li class="notification-message">
                    <a href="#">
                      <div class="media d-flex">
                        <span class="avatar avatar-sm flex-shrink-0">
                          <img
                            class="avatar-img rounded-circle"
                            alt="User Image"
                            src="{% static 'assets3/img/profiles/avatar-13.jpg' %}"
                          />
                        </span>
                        <div class="media-body flex-grow-1">
                          <p class="noti-details">
                            <span class="noti-title">Mercury Software Inc</span>
                            added a new product
                            <span class="noti-title">Apple MacBook Pro</span>
                          </p>
                          <p class="noti-time">
                            <span class="notification-time">12 mins ago</span>
                          </p>
                        </div>
                      </div>
                    </a>
                  </li>
                </ul>
              </div>
              <div class="topnav-dropdown-footer">
                <a href="#">View all Notifications</a>
              </div>
            </div>
          </li>

          <li class="nav-item dropdown has-arrow">
            <a
              href="#"
              class="dropdown-toggle nav-link"
              data-bs-toggle="dropdown"
            >
              <span class="user-img"
                ><img
                  class="rounded-circle"
                  src="{% static 'assets3/img/profiles/avatar-01.jpg' %}"
                  width="31"
                  alt="Seema Sisty"
              /></span>
            </a>
            <div class="dropdown-menu">
              <div class="user-header">
                <div class="avatar avatar-sm">
                  <img
                    src="{% static 'assets3/img/profiles/avatar-01.jpg' %}"
                    alt="User Image"
                    class="avatar-img rounded-circle"
                  />
                </div>
                <div class="user-text">
                  <h6>Seema Sisty</h6>
                  <p class="text-muted mb-0">Administrator</p>
                </div>
              </div>
              <a class="dropdown-item" href="general.html">My Profile</a>
              <a class="dropdown-item" href="general.html">Account Settings</a>
              <a class="dropdown-item" href="login.html">Logout</a>
            </div>
          </li>
        </ul>
      </div>
      

      <div class="sidebar" id="sidebar">
        <div class="sidebar-inner slimscroll">
          <div id="sidebar-menu" class="sidebar-menu">
            <ul>
              <li class="menu-title"></li>
              <li class="active">
                <a href="{% url 'useradmin:dashboard' %}"
                  ><i class="fe fe-home"></i> <span>Dashboard</span></a
                >
              </li>
              <li class="submenu">
                <a href="#"><i class="fe fe-cart"></i> <span> Orders </span>
                  <span class="menu-arrow"></span
                ></a>
                <ul style="display: none">
                  <li><a href="{% url 'useradmin:dashboard-orders' %}">All Orders</a></li>
                
                </ul>
              </li>
              <li class="submenu">
                <a href="#"
                  ><i class="fe fe-sync"></i> <span> History </span>
                  <span class="menu-arrow"></span
                ></a>
                <ul style="display: none">
                  <li><a href="call-history.html"> Call History </a></li>
                  <li><a href="group-history.html"> Group History </a></li>
                </ul>
              </li>
              <li class="submenu">
                <a href="#"
                  ><i class="fe fe-gear"></i> <span> Products </span>
                  <span class="menu-arrow"></span
                ></a>
                <ul style="display: none">
                  <li><a href="{% url 'useradmin:dashboard-products' %}">All Products</a></li>
                  <li><a href="{% url 'useradmin:dashboard-add-products' %}">Add Product </a></li>
                  </li>
                </ul>
              </li>
              <li>
                <a href="blank-page.html"
                  ><i class="fe fe-file"></i> <span>Blank Page</span></a
                >
              </li>
              <li>
                <a href="vector-maps.html"
                  ><i class="fe fe-map"></i> <span>Vector Maps</span></a
                >
              </li>
              <li>
                <a href="components.html"
                  ><i class="fe fe-vector"></i> <span>Components</span></a
                >
              </li>
              <li class="submenu">
                <a href="#"
                  ><i class="fe fe-layout"></i>
                  <span> Forms <span class="menu-arrow"></span></span
                ></a>
                <ul style="display: none">
                  <li><a href="form-basic-inputs.html">Basic Inputs</a></li>
                  <li><a href="form-input-groups.html">Input Groups</a></li>
                  <li><a href="form-horizontal.html">Horizontal Form</a></li>
                  <li><a href="form-vertical.html">Vertical Form </a></li>
                  <li><a href="form-mask.html">Form Mask</a></li>
                  <li><a href="form-validation.html">Form Validation </a></li>
                </ul>
              </li>
              <li class="submenu">
                <a href="#"
                  ><i class="fe fe-table"></i>
                  <span> Tables <span class="menu-arrow"></span></span
                ></a>
                <ul style="display: none">
                  <li><a href="tables-basic.html">Basic Tables </a></li>
                  <li><a href="data-tables.html">Data Table </a></li>
                </ul>
              </li>
              <li class="submenu">
                <a href="javascript:void(0);"
                  ><i class="fe fe-user"></i> <span>Account</span>
                  <span class="menu-arrow"></span
                ></a>
                <ul style="display: none">
                  <li>
                    <a href="{% url 'userauths:sign-out' %}"></i><span>Logout</span></a>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </div>

      </div>
      <div>
        {% block content %}
         {% endblock  %}
      </div>
    </div>


    
  </body>
 


  <script src="{% static 'assets3/js/jquery-3.6.0.min.js' %}"></script>
  <script src="{% static 'assets3/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets3/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
  <script src="{% static 'assets3/js/script.js' %}"></script>

</html>

templates/useradmin/dashboard-orders.html
{% extends 'useradmin/base.html' %}

{% load static %}
{% block content %} 

<div class="page-wrapper">
    <div class="row">
        <div class="col-md-12 d-flex">
        <div class="card card-table flex-fill">
            <div class="card-header">
            <h4 class="card-title float-start text-center">Order List</h4>
            <div class="table-search float-end">
                <input
                type="text"
                class="form-control"
                placeholder="Search"
                />
                <button class="btn" type="submit">
                <i class="fa fa-search"></i>
                </button>
            </div>
            </div>
            <div class="card-body">
            <div class="table-responsive no-radius">
                <table class="table table-hover table-center">
                <thead>
                    <tr>
                    <th>Order ID</th>
                    <th>Billing Name</th>
                    <th>Date</th>
                    <th>Total</th>
                    <th class="">Payment Status</th>
                    <th class="">Payment Method</th>
                    <th class="">View Details</th>
                    </tr>
                </thead>
                <tbody>
                    {% for l in latest_orders %}
                    <tr>
                    <td class="text-nowrap">
                        <div class="font-weight-600">#{{ l.sku }}</div>
                    </td>
                    <td class="text-nowrap">{{l.user.username|title}}</td>
                    <td class="">{{l.order_date}}</td>
                    <td class="">₵{{l.price}}</td>
                    <td class="">
                        {% if l.paid_status == True %}
                        <span class="badge badge-pill badge-success">Paid</span>
                        {% else %}
                        <span class="badge badge-pill badge-danger">Not Paid</span>
                        {% endif %}
                    </td>
                    <td>Mobile Money</td>
                    <td>
                        <a href="#" class="btn btn-xs"> View details</a>
                    </td>
                    </tr>
                    {% endfor %}
                </tbody>
                </table>
            </div>
            </div>
        </div>
        </div>
    </div>
</div>

{% endblock %}