core/urls.py
from django.urls import include, path
from core import views

from admin_notification.views import check_notification_view



app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("products/", views.product_list_view, name="product-list"),

    path("newsletter/", views.newsletter, name ="newsletter"),


    
    ################ PRODUCT ###############
    path("product/<pid>/", views.product_detail_view, name="product-detail"),
    # path("about/", about_view, name="about"),



    ########################   CATEGORY   ########################
    path("category/", views.category_list_view, name="category-list"),
    path("category/<cid>/", views.category_product_list_view, name="category-product-list"),


    ############################  VENDOR  ####################
    path("vendors/", views.vendor_list_view, name="vendor-list"),
    path("vendors/<vid>/", views.vendor_detail_view, name="vendor-detail"),


    ############## tags###########################
    path("products/tag/<slug:tag_slug>/", views.tag_list, name="tags"),

    ### Add review
    path("ajax-add-review/<int:pid>/", views.ajax_add_review, name="ajax-add-review"),

    #search
    path("search/", views.search_view, name="search"),

    #filter 
    path("filter-products/", views.filter_product, name="filter-product"),

    ####Add to cart
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),

    ## Cart page 
    path("cart/", views.cart_view, name="cart"),

    path("delete-from-cart/", views.delete_item_from_cart, name="delete-from-cart"),

        #### Update cart
    path("update-cart/", views.update_cart, name="update-cart"),


    # Checkout  URL
    path("checkout/", views.checkout_view, name="checkout"),

    #Paypal URL
    path('paypal/', include('paypal.standard.ipn.urls')),

     # Payment Successful
    path("payment-completed/", views.payment_completed_view, name="payment-completed"),

    # Payment Failed
    path("payment-failed/", views.payment_failed_view, name="payment-failed"),

     # Dahboard URL
    path("dashboard/", views.customer_dashboard, name="dashboard"),

    # Order Detail URL
    path("dashboard/order/<int:id>", views.order_detail, name="order-detail"),

    # Making address defauly
    path("make-default-address/", views.make_address_default, name="make-default-address"),

    # wishlist page
    path("wishlist/", views.wishlist_view, name="wishlist"),

    # adding to wishlist
    path("add-to-wishlist/", views.add_to_wishlist, name="add-to-wishlist"),


    # Remvoing from wishlist
    path("remove-from-wishlist/", views.remove_wishlist, name="remove-from-wishlist"),


    path("contact/", views.contact, name="contact"),
    path("ajax-contact-form/", views.ajax_contact_form, name="ajax-contact-form"),

        ############ABOUT###########
    path("about_us/", views.about_us, name="about_us"),
    path("best_Price/", views.best_price, name="best_price"),
    path("wide_assortment/", views.wide_assortment, name="wide_assortment"),
    path("free_delivery/", views.free_delivery, name="free_delivery"),
    path("easy_returns/", views.easy_returns, name="easy_returns"),
    path("great_deal/", views.great_deal, name="great_deal"),
    path("satisfaction/", views.satisfaction, name="satisfaction"),

       ###############

    path("purchase_guide/", views.purchase_guide, name="purchase_guide"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
    path("terms_of_service/", views.terms_of_service, name="terms_of_service"),


    #Notification

    path('check/notification/', check_notification_view, name="check_notifications"),










]

ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from admin_notification.views import check_notification_view


urlpatterns = [
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('secret/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("useradmin/", include("useradmin.urls")),
    path("payments/", include("payments.urls")),

    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("", include("allauth.urls")),
    path('paystack/', include('paystack.urls')),

    path('check/notification', check_notification_view, name="check_notifications"),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

newsletter/models.py
from django.db import models

# Create your models here.

class Subscribers(models.Model):
    email = models.EmailField(null=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email
    
class MailMessage(models.Model):
    title = models.CharField(max_length=200, null=True)
    message = models.TextField()


    def __str__(self):
        return self.title

core/forms.py
from django import forms
from core.models import ProductReview
from tinymce.widgets import TinyMCE


class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Write review'}))

    class Meta:
        model = ProductReview
        fields = ['review', 'rating']

class NewsletterForm(forms.Form):
    subject = forms.CharField(max_length=100)
    receivers = forms.CharField()
    message = forms.CharField(widget=TinyMCE(), label="Email content")

newsletter/forms.py
from django import forms
from .models import Subscribers, MailMessage


class SubscribersForm(forms.ModelForm):
    class Meta:
        model = Subscribers
        fields = ['email']

core/views.py
from typing import Self
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from core.forms import NewsletterForm, ProductReviewForm
from django.contrib import messages
from django.db.models import Avg
from taggit.models import Tag
from django.template.loader import render_to_string
from userauths.models import ContactUs, Profile, SubscribedUsers

import socket
from django.urls import reverse
from django.conf import settings
from paypal.standard.forms import PayPalPaymentsForm
from django.contrib.auth.decorators import login_required
from .decorators import user_is_superuser
from django.core.mail import EmailMessage


import calendar
from django.db.models import Count, Avg
from django.db.models.functions import ExtractMonth
from django.core import serializers
from django.core.paginator import Paginator

from core.models import Product,ProductImages,Category,Vendor,CartOrder,CartOrderItem,Address,ProductReview, Wishlist

# Create your views here.
def index(request):
    recently_added = Product.objects.all().order_by("-date")[:3]
    product = Product.objects.filter(product_status = "published", featured = True)
    page = Paginator(product, 10)
    page_list = request.GET.get('page')
    page = page.get_page(page_list)
    context = {
        "page":page,
        "recently_added":recently_added,
    }
    return render(request, 'core/index.html', context)

def paginate(request):
    page= request.GET.get('page', None)
    title= request.GET.get('title', None)
    
    starting_number= (page-1)*10
    ending_number= page*10

    "here you should multiply the 'page' by the number of results you want per page, in my example it's 10"
      
    result= Product.objects.filter(title= title)[starting_number:ending_number]
    
    "By [starting_number:ending_number] we specify the interval of results. Order them by date or whatever you want"
    data={result}
   
    return JsonResponse(data)



def product_list_view(request):
    product = Product.objects.filter(product_status = "published")
    categories = Category.objects.all()
    vendors = Vendor.objects.all()
    tag = Tag.objects.all()[:12]
    deals = Product.objects.all().order_by("-date")[2:6]



    context = {
        "products":product,
        "categories":categories,
        "vendors":vendors,
        "tag":tag,
        "deals":deals,
    }
    return render(request, 'core/product-list.html', context)

def category_list_view(request, tag_slug=None):
    categories = Category.objects.all()

    tag = Tag.objects.all()[:12]

    context = {
        "categories":categories,
        "tag":tag
    }
    return render(request, 'core/category-list.html', context)

def category_product_list_view(request, cid):
    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(product_status = "published", category=category)

    context = {
        "category":category,
        "products":products,
    }
    return render(request, 'core/category-product-list.html', context)


def vendor_list_view(request):
    vendors = Vendor.objects.all()
    context = {
        'vendors': vendors,
    }
    return render(request, "core/vendor-list.html", context)

def vendor_detail_view(request, vid):
    vendor = Vendor.objects.get(vid=vid)
    products = Product.objects.filter(vendor=vendor, product_status="published")
    context = {
        "vendor":vendor,
        "products":products,
    }
    return render(request, "core/vendor-detail.html", context)


def product_detail_view(request,pid):
    product = Product.objects.get(pid=pid)
    products = Product.objects.filter(category=product.category).exclude(pid=pid)

    # getting all the reviews related to the products
    reviews = ProductReview.objects.filter(product=product).order_by("-date")

    # Getting average reviews
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

    review_form = ProductReviewForm()

    make_review = True

    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user, product=product).count()

        if user_review_count > 0:
            make_review = False

    p_image = product.p_images.all()

    context = {
        "p":product,
        "p_image":p_image,
        "products":products,
        "reviews":reviews,
        "average_rating":average_rating,
        "review_form":review_form,
        "make_review":make_review,
    }

    return render(request, "core/product-detail.html", context)

def tag_list(request, tag_slug=None):
    products = Product.objects.filter(product_status="published").order_by("-id")

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])

    context = {
        "products":products,
        "tag":tag
    }
    return render(request, "core/tag.html", context)

def ajax_add_review(request, pid):
    product = Product.objects.get(pk=pid)
    user = request.user

    review = ProductReview.objects.create(
        user = user,
        product = product,
        review = request.POST['review'],
        rating = request.POST['rating'],
    )

    context = {
        'user': user.username,
        'review': request.POST['review'],
        'rating': request.POST['rating'],
    }

    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg("rating"))

    return JsonResponse(
        {
           'bool': True,
           'context':context,
           'average_reviews': average_reviews
        }
    )


def search_view(request):
    query = request.GET.get("q")

    products = Product.objects.filter(title__icontains = query).order_by("-date")

    context = {
        "products": products,
        "query": query,
    }

    return render(request, "core/search.html", context)


def filter_product(request):
    categories = request.GET.getlist("category[]")
    vendors = request.GET.getlist("vendor[]")

    min_price = request.GET['min_price']
    max_price = request.GET['max_price']

    products = Product.objects.filter(product_status="published").order_by("-id").distinct()

    products = products.filter(price__gte=min_price)
    products = products.filter(price__lte=max_price)

    if len(categories) > 0:
        products = products.filter(category__id__in=categories).distinct()

    if len(vendors) > 0:
        products = products.filter(vendor__id__in=vendors).distinct()

    data = render_to_string("core/async/product_list.html", {"products": products})

    return JsonResponse({"data":data})

def add_to_cart(request):
    cart_product = {}

    cart_product[str(request.GET['id'])] = {
        'title':request.GET['title'],
        'qty': request.GET['qty'],
        'price': request.GET['price'],
        'image':request.GET['image'],
        'pid':request.GET['pid'],
    }

    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:

            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = int(cart_product[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data


    else:
        request.session['cart_data_obj'] = cart_product
    return JsonResponse({"data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj'])})

def cart_view(request):

    cart_total_amount = 0

    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
            # delivery_fee = (105/100) * float(cart_total_amount)
            # delivery_fee_total = (5/100) * float(cart_total_amount)

        return render(request, "core/cart.html", {"cart_data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount ,})
    else:
        messages.warning(request, "Your cart is Empty")
        return redirect("core:index")
    
    


def delete_item_from_cart(request):
    product_id = str(request.GET['id'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data
    
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])

    context = render_to_string("core/async/cart-list.html", {"cart_data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})
    return JsonResponse({"data": context, 'totalcartitems': len(request.session['cart_data_obj'])})


def update_cart(request):
    product_id = str(request.GET['id'])
    product_qty = request.GET['qty']

    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = product_qty
            request.session['cart_data_obj'] = cart_data
    
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])

newsletter/views.py
from django.shortcuts import render
from .forms import SubscribersForm
# Create your views here.


def index(request):
    if request.method == 'POST':
        form = SubscribersForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = SubscribersForm()
    form = SubscribersForm()

    context ={
        'form': form,
    }
    return render(request, 'core/index.html', context)

templates/core/best_price.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

   <style>
    .hi{
        text-align: center;
        font-size: 50px;
    }
    p{
        text-align: center;
        line-height: 1.4;
        font-size: medium;
    }
   </style>
    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="{% url 'core:index' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span><a href="{% url 'core:about_us' %}">About us</a><span></span> Best Price & and Offers
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-6 mb-50 mt-50 text-center">
                    <div class="featured-card">
                        <img src="{% static 'assets/imgs/theme/icons/icon-1.svg' %}" alt="" />
                        <h4 class="hi">Best Prices & Offers</h4>
                        <p>Adepa Global Marketplace strives to offer competitive prices on a wide range of products.
                         Customers can find great deals and discounts on verious items, making it go-to platform for budget-conscious shoppers.
                         The platform also offers special promotions, seasonal sales, and exclusive discounts to provide additional value customers.
                        </p>
                        <a class="btn btn-outline-warning" href="{% url 'core:about_us' %}">Back</a>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

templates/core/cart.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content  %}
    <main class="main bg-light" id="cart-list">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="{% url 'core:index' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop
                    <span></span> Cart
                </div>
            </div>
            
        </div>
        <section class="newsletter mb-15 mt-15">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="position-relative newsletter-inner">
                            {% comment %} {% if not user.is_authenticated %} {% endcomment %}
                            <div class="newsletter-content">
                                <h2 class="mb-20 text-white">
                                    Stay home & get your daily <br /> needs from our shop
                                </h2>
                                <p class="mb-45 text-white text-muted">Start Your Daily Shopping with <span class="text-brand">AdepaMarket</span></p>
                                {% comment %} <form class="form-subcriber d-flex shadow-sm">
                                    <input type="email" placeholder="Your emaill address" />
                                    <button class="btn" type="submit">Subscribe</button>
                                </form> {% endcomment %}
                            </div>
                            {% comment %} {% endif %} {% endcomment %}
                            {% comment %} <img src="{% static 'assets/imgs/banner/banner-9.png' %}" alt="newsletter" /> {% endcomment %}
                        </div>
                    </div>
                </div>
            </div>
        </section>      
        <div class="container pt-40">
            {% comment %} <p class="fw-10">Delivery Fee: <strong>₵0.00</strong></p> {% endcomment %}
            &nbsp;
            <h5 class="mb-10">Subtotal: <strong>₵{{cart_total_amount|floatformat:2}}</strong></h5>
            <hr>
            {% if totalcartitems %}
            <button href="{% url 'core:checkout' %}" style="height: 50px;border-radius: 20px;" class="w-100 btn btn-warning text-dark shadow-sm"><a class="text-dark" href="{% url 'core:checkout' %}">Proceed to checkout ({{totalcartitems}} Item{{totalcartitems|pluralize}})</a></button>
            {% endif %}
        </div>
        <div class="container mb-80 mt-50">
            <div class="row">
                <div class="col-lg-8 mb-40">
                    <div class="d-flex justify-content-between">
                        <h6 class="text-body"><a href="#" class="text-muted"><i class="fi-rs-trash mr-5"></i>Clear Cart</a></h6>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 justify-content-between">
                    {% for product_id, item in cart_data.items %}
                    <div class="product-cart-wrap shadow-sm rounded-3 mb-10" >
                        <div class="row">
                                <div class="col-sm-4 product-img-action-wrap" >
                                    <p class="text-muted">Product</p>
                                    <div class="product-img"style="text-align: center;">
                                        <div class="product-img-inner">
                                            <div class="image product-thumbnail"><img style="width: 100px;" src="{{item.image}}" alt="#"></div>
                                        </div>
                                    </div>
                                </div>
                               
                                <br>
                                <div class="col-sm-4 product-content-wrap pt-40 text-center" >
                                    <p class="text-muted">QTY Unit-price</p>
                                    <h2><a href="{% url 'core:product-detail' item.pid %}">{{item.title|truncatechars:15}}</a></h2>
                                    <div class="product-price price" data-title="price">
                                        <input style="width: 60px;" min="1" value="{{item.qty}}" type="number" class="product-qty-{{ product_id }}">
                                        <span>×</span>
                                        <span>₵{{item.price|floatformat:2}}</span>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="text-center" data-title="price">
                                    </div>
                                    <div class="action text-center mb-15 pt-40">
                                        <p class="text-muted">Subtotal</p>
                                        <h4 style="display: inline-flex;" class="text-brand mb-10">₵{% widthratio item.price 1 item.qty %}</h4>
                                        <br>
                                        <button style="border: none;background: none;" class="action text-body update-item" data-item="{{ product_id }}"><i class="fi-rs-refresh"></i></button>
                                        &nbsp;&nbsp;&nbsp;&nbsp;
                                        <button style="border: none;background: none;" class="action text-body delete-item" data-item="{{ product_id }}"><i class="fi-rs-trash"></i></button>
                                    </div>
                                </div>
                            
                        </div>
                    </div>
                    
                    {% endfor %}
                </div>
             
                <div class="col-lg-4 order-md-last pt-10 border shadow-sm">
                        <h4 class="d-flex justify-content-between align-items-center mb-3">
                          <span class="text-primary">Summary</span>
                          <span class="badge bg-success rounded-pill">{{totalcartitems}}</span>
                        </h4>
                        <ul class="list-group mb-3">
                          <li class="list-group-item d-flex justify-content-between lh-sm">
                            <div>
                              <h6 class="my-0">Delivery Fee</h6>
                              <small class="text-muted">5% on Subtotal</small>
                            </div>
                            <span class="text-muted">₵0.00</span>
                          </li>
                          <li class="list-group-item d-flex justify-content-between">
                            <span>Total (GHS)</span>
                            <strong>₵{{cart_total_amount|floatformat:2}}</strong>
                          </li>
                        </ul>
                
                        {% if totalcartitems %}
                        <form class="card p-2">
                          <div class="input-group">
                            <a href="{% url 'core:checkout' %}" type="submit" class="btn btn-success w-100">Checkout</a>
                        </div>
                        </form>
                       {% endif %}      
                       <img class="wow fadeIn animated w-100"  src="{% static 'assets/imgs/theme/payment-method-2.png' %}" alt="" />                  
                       <img class="wow fadeIn animated w-100"  src="{% static 'assets/imgs/theme/payment-method.png' %}" alt="" />                  
                </div>
    
            </div>
        </div>
    </main>
{% endblock %}

templates/core/easy_returns.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

   <style>
    .hi{
        text-align: center;
        font-size: 50px;
    }
    p{
        text-align: center;
        line-height: 1.4;
        font-size: medium;
    }
   </style>
    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="{% url 'core:index' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span><a href="{% url 'core:about_us' %}">About us</a><span></span> Easy returns
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-6 mb-50 mt-50 text-center">
                    <div class="featured-card">
                        <img src="{% static 'assets/imgs/theme/icons/icon-4.svg' %}" alt="" />
                        <h4 class="hi">Easy Returns</h4>
                        <p>
                           Adepa Global Marketplace understands that customer satisfaction is paramount. Therefore, it offers a hassle-free and
                           transparent return policy, allowing caustomers to return products easily if they are not satisfied with their 
                           purchase. This provides peace of mind to customers, knowing that they can shop with confidence and the option to
                           return or exchange items if needed.
                        </p>
                        <a class="btn btn-outline-info" href="{% url 'core:about_us' %}">Back</a>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

templates/core/newsletter.html
{% extends 'partials/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


<main class="container bg-light">
    <div class="row mt-5 pt-5">
        <div class="col-md-6 offset-md-3 content-section mb-100 mt-100">
            <form class="bg-white border shadow-sm pl-30 pr-30 pt-20 pb-20" method="POST">
                {% csrf_token %}
                {{ form }}
                {{ form.media  }}
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Send</button>
                </div>
            </form>
        </div>
    </div>
</main>
{% endblock content %}

templates/core/satisfaction.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

   <style>
    .hi{
        text-align: center;
        font-size: 50px;
    }
    p{
        text-align: center;
        line-height: 1.4;
        font-size: medium;
    }
   </style>
    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="{% url 'core:index' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span><a href="{% url 'core:about_us' %}">About us</a><span></span> satisfaction
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-6 mb-50 mt-50 text-center">
                    <div class="featured-card">
                        <img src="{% static 'assets/imgs/theme/icons/icon-5.svg' %}" alt="" />
                        <h4 class="hi">100% Satisfaction</h4>
                        <p class="">
                           Adepa Global Marketplace offers is commited to ensuring 100% customer satifaction. The platform strives to provide
                           excellent customer service service through prompt responses to inquiries, effecient order processing and reliable support.
                           Customer fedback and reviews are valued, and the business takes neccessart actions to address any issues or concerns
                            to ensure a positive shopping experience.
                        </p>
                        <a class="btn btn-outline-info" href="{% url 'core:about_us' %}">Back</a>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}