core/urls.py
from django.urls import include, path
from core import views

from admin_notification.views import check_notification_view



app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("products/", views.product_list_view, name="product-list"),

    path("newsletter/", views.newsletter, name ="newsletter"),


    
    ################ PRODUCT ###############
    path("product/<pid>/", views.product_detail_view, name="product-detail"),
    # path("about/", about_view, name="about"),



    ########################   CATEGORY   ########################
    path("category/", views.category_list_view, name="category-list"),
    path("category/<cid>/", views.category_product_list_view, name="category-product-list"),


    ############################  VENDOR  ####################
    path("vendors/", views.vendor_list_view, name="vendor-list"),
    path("vendors/<vid>/", views.vendor_detail_view, name="vendor-detail"),


    ############## tags###########################
    path("products/tag/<slug:tag_slug>/", views.tag_list, name="tags"),

    ### Add review
    path("ajax-add-review/<int:pid>/", views.ajax_add_review, name="ajax-add-review"),

    #search
    path("search/", views.search_view, name="search"),

    #filter 
    path("filter-products/", views.filter_product, name="filter-product"),

    ####Add to cart
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),

    ## Cart page 
    path("cart/", views.cart_view, name="cart"),

    path("delete-from-cart/", views.delete_item_from_cart, name="delete-from-cart"),

        #### Update cart
    path("update-cart/", views.update_cart, name="update-cart"),


    # Checkout  URL
    path("checkout/", views.checkout_view, name="checkout"),

    #Paypal URL
    path('paypal/', include('paypal.standard.ipn.urls')),

     # Payment Successful
    path("payment-completed/", views.payment_completed_view, name="payment-completed"),

    # Payment Failed
    path("payment-failed/", views.payment_failed_view, name="payment-failed"),

     # Dahboard URL
    path("dashboard/", views.customer_dashboard, name="dashboard"),

    # Order Detail URL
    path("dashboard/order/<int:id>", views.order_detail, name="order-detail"),

    # Making address defauly
    path("make-default-address/", views.make_address_default, name="make-default-address"),

    # wishlist page
    path("wishlist/", views.wishlist_view, name="wishlist"),

    # adding to wishlist
    path("add-to-wishlist/", views.add_to_wishlist, name="add-to-wishlist"),


    # Remvoing from wishlist
    path("remove-from-wishlist/", views.remove_wishlist, name="remove-from-wishlist"),


    path("contact/", views.contact, name="contact"),
    path("ajax-contact-form/", views.ajax_contact_form, name="ajax-contact-form"),

        ############ABOUT###########
    path("about_us/", views.about_us, name="about_us"),
    path("best_Price/", views.best_price, name="best_price"),
    path("wide_assortment/", views.wide_assortment, name="wide_assortment"),
    path("free_delivery/", views.free_delivery, name="free_delivery"),
    path("easy_returns/", views.easy_returns, name="easy_returns"),
    path("great_deal/", views.great_deal, name="great_deal"),
    path("satisfaction/", views.satisfaction, name="satisfaction"),

       ###############

    path("purchase_guide/", views.purchase_guide, name="purchase_guide"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
    path("terms_of_service/", views.terms_of_service, name="terms_of_service"),


    #Notification

    path('check/notification/', check_notification_view, name="check_notifications"),










]

ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from admin_notification.views import check_notification_view


urlpatterns = [
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('secret/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("useradmin/", include("useradmin.urls")),
    path("payments/", include("payments.urls")),

    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("", include("allauth.urls")),
    path('paystack/', include('paystack.urls')),

    path('check/notification', check_notification_view, name="check_notifications"),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path('subscribe/', views.subscribe, name='subscribe'),
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('social/signup', views.signup_redirect, name='signup_redirect'),

    # path("newsletter", views.newsletter, name ="newsletter"),


    path("password-reset/", views.password_reset_request, name="reset-password"),
    path("password-change/", views.password_change, name="password-change"),
    path("reset/<uidb64>/<token>", views.passwordResetConfirm, name="password-reset-confirm"),

    path("profile/update/", views.profile_update, name="profile-update"),
]

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, SetPasswordForm, PasswordResetForm
from userauths.models import User, Profile
from django.contrib.auth import get_user_model
from tinymce.widgets import TinyMCE



from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Username"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder":"Email"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Password"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Confirm Password"}))

    class Meta:
        model = User
        fields = ['username', 'email']

class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Username or Email'}),
        label="Username or Email*")

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}))

    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox())




class ProfileForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Full Name"}))
    bio = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Bio"}))
    phone = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Phone"}))

    class Meta:
        model = Profile
        fields = ['full_name', 'image', 'bio', 'phone']

class SetPasswordForm(SetPasswordForm):
    class Meta:
        model = get_user_model()
        fields = ['new_password1', 'new_password2']

class PasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(PasswordResetForm, self).__init__(*args, **kwargs)


    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox())

userauths/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponseRedirect
from userauths.forms import UserLoginForm, UserRegisterForm, ProfileForm, SetPasswordForm, PasswordResetForm
from django.contrib.auth import login, authenticate, logout, get_user_model
from django.contrib import messages
from userauths.models import Profile
from .models import SubscribedUsers

from django.core.validators import validate_email
from django.core.exceptions import ValidationError


from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage
from userauths.tokens import account_activation_token
from django.db.models.query_utils import Q

from django.contrib.auth.decorators import login_required
from .decorators import user_is_superuser






# User = settings.AUTH_USER_MODEL
#Addded by me

def signup_redirect(request):
    messages.error(request, "Something wrong here, it may be that you already have an account!")
    return redirect("core:index")



def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except:
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        messages.success(request, "Thank you for your email confirmation. Now you can login your account.")
        return redirect("userauths:sign-in")
    else:
        messages.error(request, "Activation link is invalid!")

    return redirect('core:index')


def activateEmail(request, user, to_email):
    mail_subject = "Activate your user account."
    message = render_to_string("userauths/activate_account.html", {
        'user': user.username,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        "protocol": 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    if email.send():
        messages.success(request, f'Dear <b>{user}</b>, please go to you email <b> {to_email} </b> inbox and click on \
                received activation link to confirm and complete the registration. <b>Note:</b> Check your spam folder.')
    else:
        messages.error(request, f'Problem sending email to {to_email}, check if you typed it correctly.')





def register_view(request):
    
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            user = form.save()
            activateEmail(request, user, form.cleaned_data.get('email'))

            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect(request.META.get("HTTP_REFERER", "core:index")) 

        else:
            for error in list(form.errors.values()):
                messages.error(request, error)
        
    else:
        form = UserRegisterForm()


    context = {
        'form': form,
    }
    return render(request, "userauths/sign-up.html", context)


def login_view(request):
    if request.user.is_authenticated:
        messages.error(request, f"Hello! You are already logged in")
        return redirect(request.META.get("HTTP_REFERER", "core:index"))  

    if request.method == "POST":
        
        form = UserLoginForm(request=request, data=request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data["username"],
                password=form.cleaned_data["password"],
            )
            if user is not None:
                login(request, user)
                messages.success(request, f"Hello <b>{user.username}</b>! You have been logged in")
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                else:
                    return redirect(request.META.get("HTTP_REFERER", "core:index")) 

        else:
            for key, error in list(form.errors.items()):
                if key == 'captcha' and error[0] == 'This field is required.':
                    messages.error(request, "You must pass the reCAPTCHA test")
                    continue
                
                messages.error(request, error) 

    form = UserLoginForm()

    return render(
        request=request,
        template_name="userauths/sign-in.html",
        context={"form": form}
        )

        
@login_required
def logout_view(request):

    logout(request)
    messages.success(request, "You logged out.")
    return redirect("userauths:sign-in")

@login_required
def profile_update(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            messages.success(request, "Profile Updated Successfully.")
            return redirect("core:dashboard")
    else:
        form = ProfileForm(instance=profile)

    context = {
        "form": form,
        "profile": profile,
    }

    return render(request, "userauths/profile-edit.html", context)

@login_required
def password_change(request):
    user = request.user
    if request.method == 'POST':
        form = SetPasswordForm(user, request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your password has been changed, Login to continue")
            return redirect("userauths:sign-in")
        else:
            for error in list(form.errors.values()):
                messages.error(request, error)


    form = SetPasswordForm(user)
    return render(request, 'userauths/password_reset_confirm.html', {'form': form})


def password_reset_request(request):
    form = PasswordResetForm()
    if request.method == 'POST':
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            user_email = form.cleaned_data['email']
            associated_user = get_user_model().objects.filter(Q(email=user_email)).first()
            if associated_user:
                subject = "Password Reset request"
                message = render_to_string("userauths/template_reset_password.html", {
                    'user': associated_user,
                    'domain': get_current_site(request).domain,
                    'uid': urlsafe_base64_encode(force_bytes(associated_user.pk)),
                    'token': account_activation_token.make_token(associated_user),
                    "protocol": 'https' if request.is_secure() else 'http'
                })
                email = EmailMessage(subject, message, to=[associated_user.email])
                if email.send():
                    messages.success(request,
                        """"
                        <h2>Password reset sent</h2>
                        <p>
                            We've emailed you instructions for setting your password, If an account exist with the email you provided.
                            You should receive them shortly. <br> If you receive an email, please make sure you've entered the address
                            you registered with, and check your spam folder
                        </p>

                        """
                    )
                else:
                    messages.error(redirect, "Probelm sending reset password email, <b>SERVER PROBLEM</b>")

            return redirect("core:index")

        for key, error in list(form.errors.items()):
            if key == 'captcha' and error[0] == 'This field is required.':
                messages.error(request, "You must pass the reCAPTCHA test")
                continue
    form = PasswordResetForm()     
    context = {
        'form': form,
    }

    return render(request=request, template_name='userauths/reset-password.html', context=context)

def passwordResetConfirm(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except:
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        if request.method == 'POST':
            form = SetPasswordForm(user, request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "Your password has been set. You may go ahead and <b>log in</b> now.")
                return redirect("userauths:sign-in")
            else:
                for error in list(form.errors.values()):
                    messages.error(request, error)

        form = SetPasswordForm(user)
        return render(request, 'userauths/password_reset_confirm.html', {'form': form})
    else:
        messages.error(request, "Link is expired")

    messages.error(request, 'Something went wrong, redirecting back to Homepage')
    return redirect("core:index")

def subscribe(request):
    if request.method == 'POST':
        email = request.POST.get('email', None)

        if not email:
            messages.error(request, "You must type legit email to subscribe to a Newsletter")
            return redirect("core:index")

        if get_user_model().objects.filter(email=email).first():
            messages.error(request, f"Found registered user with associated {email} email. You must login to subscribe or unsubscribe.")
            return redirect(request.META.get("HTTP_REFERER", "core:index")) 

        subscribe_user = SubscribedUsers.objects.filter(email=email).first()

templates/userauths/activate_account.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

{{ protocol }}://{{ domain }}{% url 'userauths:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/userauths/reset-password.html
{% extends 'partials/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .b-example-divider {
      height: 3rem;
      background-color: rgba(0, 0, 0, .1);
      border: solid rgba(0, 0, 0, .15);
      border-width: 1px 0;
      box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
      flex-shrink: 0;
      width: 1.5rem;
      height: 100vh;
    }

    .bi {
      vertical-align: -.125em;
      fill: currentColor;
    }

    .nav-scroller {
      position: relative;
      z-index: 2;
      height: 2.75rem;
      overflow-y: hidden;
    }

    .nav-scroller .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }

    .form-signin {
        max-width: 330px;
        padding: 15px;
      }
      
      .form-signin .form-floating:focus-within {
        z-index: 2;
      }
      
      .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
      }
      
      .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
      }
  </style>



    <main class="main pages bg-light">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Account <span></span> Password Recovery
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            <div class="col-lg-6 pr-30 d-none d-lg-block">
                                <img class="border-radius-15" src="{% static 'assets/imgs/page/login-1.png' %}" alt="" />
                            </div>
                            <div class="col-lg-6 col-md-8">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white border pr-30 pl-30 pt-30 pb-30">
                                        <div class="heading_s1">
                                            <h3 class="mb-5 text-center">Enter email to recover password</h3>
                                            <p class="mb-30">Don't have an account? <a href="{% url 'userauths:sign-up' %}">Create here</a></p>
                                            {% comment %} <p class="mb-30">Forgot Password? <a href="{% url 'userauths:reset-password' %}">Recover</a></p> {% endcomment %}
                                        </div>
                                        <form method="POST" class="my-class">
                                            {% csrf_token %}
                                            <fieldset class="form-group">
                                              <legend class="border-bottom mb-4">A link will be sent to this email if it exists</legend>
                                                  {{ form }}
                                              </div>
                                             </fieldset>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-heading w-100 btn-block hover-up" name="login">Log in</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    

{% endblock content %}

templates/userauths/sign-in.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}
{% load socialaccount %}

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .b-example-divider {
      height: 3rem;
      background-color: rgba(0, 0, 0, .1);
      border: solid rgba(0, 0, 0, .15);
      border-width: 1px 0;
      box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
      flex-shrink: 0;
      width: 1.5rem;
      height: 100vh;
    }

    .bi {
      vertical-align: -.125em;
      fill: currentColor;
    }

    .nav-scroller {
      position: relative;
      z-index: 2;
      height: 2.75rem;
      overflow-y: hidden;
    }

    .nav-scroller .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }

    .form-signin {
        max-width: 330px;
        padding: 15px;
      }
      
      .form-signin .form-floating:focus-within {
        z-index: 2;
      }
      
      .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
      }
      
      .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
      }
  </style>



    <main class="main pages bg-light">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Pages <span></span> Sign-in
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            <div class="col-lg-6 pr-30 d-none d-lg-block">
                                <img class="border-radius-15" src="{% static 'assets/imgs/page/login-1.png' %}" alt="" />
                            </div>
                            <div class="col-lg-6 col-md-6">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white border pr-30 pl-30 pt-30 pb-30">
                                        <div class="heading_s1">
                                            <h1 class="mb-5 text-center">Login</h1>
                                            <p class="mb-30">Don't have an account? <a href="{% url 'userauths:sign-up' %}">Create here</a></p>
                                            {% comment %} <p class="mb-30">Forgot Password? <a href="{% url 'userauths:reset-password' %}">Recover</a></p> {% endcomment %}
                                        </div>
                                        <form method="POST" class="my-class">
                                            {% csrf_token %}
                                            <fieldset class="form-group">
                                              <legend class="border-bottom mb-4">Log In</legend>
                                                  {{ form }}
                                                  {% if request.GET.next %}
                                                  <input type="hidden" name="next" value="{{ request.GET.next }}">
                                                  {% endif %}
                                              </div>
                                             </fieldset>
                                            <div class="form-group">
                                                <button class="btn btn-outline-info" name="login">Login</button>
                                                <button class="btn btn-outline-info">
                                                  <a href="{% provider_login_url 'google' %}?next=/">
                                                    <i class="fab fa-google"></i>
                                                    Login with google
                                                  </a>
                                                </button>
                                            </div>
                                        </form>
                                        <small>
                                          <a href="{% url 'userauths:reset-password' %}">Forgot Password?</a>
                                        </small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    
{% endblock%}
    

templates/userauths/template_reset_password.html
{% load static %}
{% autoescape off %}
        Hello {{ user.username|title }},

        We received a request to reset the password for your account for this email address. To initiate the password reset process for your account, click the link below.

        {{ protocol }}://{{ domain }}{% url 'userauths:password-reset-confirm' uidb64=uid token=token %}

        This link can only be used once. If you need to reset your password again, please visit {{ protocol }}://{{domain}} and request another reset.

        If you did not make this request, you can simply ignore this email.

        Sincerely,
        Explorer

{% endautoescape %}